<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <PackageProjectUrl>https://github.com/m-bergstrom/PiForge.Branding</PackageProjectUrl>
        <RepositoryUrl>https://github.com/m-bergstrom/PiForge.Branding</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageVersion>1.0.4</PackageVersion>
        <PackageId>PiForge.Branding</PackageId>
        <Authors>Matthew Bergstrom</Authors>
        <Copyright>© 2025 Matthew Bergstrom</Copyright>
        <IncludeBuildOutput>false</IncludeBuildOutput>
        <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
        <PackageIcon>piforge_dark_rounded_128x128.png</PackageIcon>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="contentFiles\any\any\piforge_dark_rounded_128x128.png" Pack="true" PackagePath="contentFiles/any/any" />
    </ItemGroup>
    <ItemGroup>
        <Content Include="buildTransitive\PiForge.Branding.props" Pack="true" PackagePath="buildTransitive" />
        <Content Include="buildTransitive\PiForge.Branding.targets" Pack="true" PackagePath="buildTransitive" />
    </ItemGroup>
    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="\" />
        <None Include="LICENSE" Pack="true" PackagePath="\" />
        <None Include="contentFiles\any\any\piforge_dark_rounded_128x128.png" Pack="true" PackagePath="\" />
    </ItemGroup>

</Project>